type: task_block
title: Classify Data
icon: ":carbon:table-split:"
executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: climate_data
    json_schema:
      contentMediaType: oomol/var
  - handle: weekly_stats
    json_schema:
      contentMediaType: oomol/var
  - handle: sigma1
    json_schema:
      type: integer
    value: 3
  - handle: sigma2
    json_schema:
      type: integer
    value: 2
  - handle: year_from
    json_schema:
      type: integer
    value: 2010
  - handle: year_to
    json_schema:
      type: integer
    value: 2020
  - handle: indicator
    json_schema:
      type: string
  - handle: levels
    json_schema:
      type: array
      items:
        type: string
outputs_def:
  - handle: disaster
    json_schema:
      contentMediaType: oomol/var
